# Generated by Django 5.2.1 on 2025-05-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='published_data',
            new_name='published_date',
        ),
    ]
